API_URL: "http://124.61.84.96:8502"
SOCKET_URL: "ws://124.61.84.96:8502/chat"
CHATLIST_IMG_URL: "https://i.postimg.cc/j5HJHm0Q/image.png"
CREATECHAR_IMG_URL: "https://i.postimg.cc/TYVfRxjc/image.png"
MAX_TAGS: 5