login: False
login_window: "login"
user: None
transition: False
header_btn: None
start_chat: False
character_data: None
chatroom_data: None
select_img: "https://i.postimg.cc/q7Ds0VGf/image.png"
modify_data: None
mypage_view: "mypage"
chat_history: []
chatroom_id: None
new_chat: False
user_profile: "https://i.postimg.cc/q7Ds0VGf/image.png"
char_profile: "https://i.postimg.cc/q7Ds0VGf/image.png"
delete_character: False
login_pop: False