login: False
login_window: "login"
user: None
transition: False

header_btn: None

chat_start: False
character_data: None

select_img: "https://i.postimg.cc/q7Ds0VGf/image.png"
modified_data: None

mypage_view: None